### ISSUE TITLE
converting MarkDown badges

### ISSUE THREAD

**Issue by Borda** [readthedocs/recommonmark#152] opened 2019-04-29 16:38 UTC
I wanted to include my [readme](https://github.com/Borda/py_sample-project/blob/master/README.md) into generated sphinx documentation, so I used this package as an extension for sphinx but the conversion of badges still preserves some captions which are not much wanted, see the following illustration from [readthedoc](https://py-sample-project.readthedocs.io/en/latest)...
![recommonmark-badges](https://user-images.githubusercontent.com/6035284/56911689-d069ec80-6aad-11e9-91f7-1a3c5d779089.png)
Is there a simple way how to fix it? I found that for example, [m2r](https://github.com/miyakogi/m2r) does the job well...

**Comment by Borda** [comment] 2019-07-04 18:30
@ericholscher @pfultz2 @tqchen @agjohnson ^^

**Comment by oz123** [comment] 2019-07-24 21:25
I am having the same issue. It seems that alt text is always shown.

**Comment by Borda** [comment] 2019-10-25 11:06
@ericholscher @pfultz2 @tqchen @agjohnson ^^

**Comment by eric-wieser** [comment] 2020-05-28 08:40
Duplicate of #88. This can be closed, as it was fixed in #150.

**Closed** 2020-05-28 15:23 UTC
