### ISSUE TITLE
recommonmark 0.7.1 crash: AttributeError: 'NoneType' object has no attribute 'append' in visit_paragraph

### ISSUE THREAD

**Issue by arielf** [readthedocs/recommonmark#223] opened 2021-04-19 21:02 UTC
Attaching full log + stack-trace.
[sphinx-err-6iv2a531.log](https://github.com/readthedocs/recommonmark/files/6339051/sphinx-err-6iv2a531.log)

Workaround:
Found that including the text:
```
WIP ...
```
in the `*.md` file that was being processed during the crash, is what is triggering it
Removing this particular text avoids the crash.

**Comment by astrojuanlu** [comment] 2021-04-19 21:43
Probably a duplicate of #159.

**Closed** 2022-03-24 20:30 UTC
