### ISSUE TITLE
Error on inline math

### ISSUE THREAD

**Issue by leokoppel** [readthedocs/recommonmark#120] opened 2018-09-30 01:13 UTC
There is an exception when processing markdown file containing inline math via Sphinx. The same markdown file previously worked.
[Here is a Travis log](https://travis-ci.com/wavelab/wave_geometry/jobs/148760758).

The immediate error message is
```
Exception occurred:
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/docutils/parsers/rst/roles.py", line 356, in math_role
    text = rawtext.split('`')[1]
IndexError: list index out of range
```

I can also reproduce on my machine by adding an inline math expression
  
     `$ a $`

to `tests/sphinx_custom_md/index.markdown` and running `python3 -m unittest -q tests.test_sphinx.CustomExtensionTests`. Here is the full output

```
Running Sphinx v1.7.9
making output directory...
loading pickled environment... not yet created
building [mo]: all of 0 po files
building [html]: all source files
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index
/usr/local/lib/python3.5/dist-packages/docutils/io.py:245: DeprecationWarning: 'U' mode is deprecated
  self.source = open(source_path, mode, **kwargs)
======================================================================
ERROR: test_integration (tests.test_sphinx.CustomExtensionTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/recommonmark/tests/test_sphinx.py", line 66, in test_integration
    ['</table>']
  File "/code/recommonmark/tests/test_sphinx.py", line 23, in _run_test
    app.build(force_all=True)
  File "/usr/local/lib/python3.5/dist-packages/sphinx/application.py", line 325, in build
    self.builder.build_all()
  File "/usr/local/lib/python3.5/dist-packages/sphinx/builders/__init__.py", line 299, in build_all
    self.build(None, summary='all source files', method='all')
  File "/usr/local/lib/python3.5/dist-packages/sphinx/builders/__init__.py", line 355, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/usr/local/lib/python3.5/dist-packages/sphinx/environment/__init__.py", line 568, in update
    self._read_serial(docnames, self.app)
  File "/usr/local/lib/python3.5/dist-packages/sphinx/environment/__init__.py", line 587, in _read_serial
    self.read_doc(docname, app)
  File "/usr/local/lib/python3.5/dist-packages/sphinx/environment/__init__.py", line 662, in read_doc
    doctree = read_doc(self.app, self, self.doc2path(docname))
  File "/usr/local/lib/python3.5/dist-packages/sphinx/io.py", line 302, in read_doc
    pub.publish()
  File "/usr/local/lib/python3.5/dist-packages/docutils/core.py", line 218, in publish
    self.apply_transforms()
  File "/usr/local/lib/python3.5/dist-packages/docutils/core.py", line 199, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/usr/local/lib/python3.5/dist-packages/sphinx/transforms/__init__.py", line 96, in apply_transforms
    Transformer.apply_transforms(self)
  File "/usr/local/lib/python3.5/dist-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/code/recommonmark/recommonmark/transform.py", line 343, in apply
    self.traverse(self.document)
  File "/code/recommonmark/recommonmark/transform.py", line 313, in traverse
    self.traverse(child)
  File "/code/recommonmark/recommonmark/transform.py", line 313, in traverse
    self.traverse(child)
  File "/code/recommonmark/recommonmark/transform.py", line 303, in traverse
    newnode = self.find_replace(c)
  File "/code/recommonmark/recommonmark/transform.py", line 287, in find_replace
    newnode = self.auto_inline_code(node)
  File "/code/recommonmark/recommonmark/transform.py", line 214, in auto_inline_code
    return self.state_machine.run_role('math', content=content)
  File "/code/recommonmark/recommonmark/states.py", line 134, in run_role
    content=content)
  File "/usr/local/lib/python3.5/dist-packages/docutils/parsers/rst/roles.py", line 356, in math_role
    text = rawtext.split('`')[1]
IndexError: list index out of range
```

[Here is a Travis log](https://travis-ci.com/wavelab/wave_geometry/jobs/144225146) from a few weeks ago where the same file is processed successfully. Unfortunately I can't tell what the relevant difference is. (Some version numbers have changed, but installing the older Sphinx on my own machine, for example, does not remove the problem.)

**Comment by Anntoin** [comment] 2018-10-06 23:49
This caught me out too. Sphinx needs to have a math extension enabled.

I think this might actually be a minor bug in docutils as if you work around it there is a useful warning message.

> WARNING: using "math" markup without a Sphinx math extension active, please use one of the math extensions descri bed at http://sphinx-doc.org/en/master/ext/math.html

**Comment by ericholscher** [comment] 2018-10-11 18:34
Any more details on how to fix it? I did a PR that hacked it, but it would be useful if it's just a `conf.py` change. I see it's a Sphinx 1.8 issue.

**Comment by ericholscher** [comment] 2018-10-12 10:36
I'm still getting the error on Sphinx 1.8. 

In sphinx 1.7 it uses Sphinx's `math` role:

```
ipdb> inspect.getfile(role_fn)
'/Users/eric/.pyenv/versions/3.6.6/lib/python3.6/site-packages/sphinx/ext/mathbase.py'
```

In Sphinx 1.8 it uses the docutils one, which is where this error comes from:

```
ipdb> inspect.getfile(role_fn)
'/Users/eric/.pyenv/versions/3.6.6/lib/python3.6/site-packages/docutils/parsers/rst/roles.py'
```

**Comment by leokoppel** [comment] 2018-10-20 04:03
Thanks @Anntoin, that explains why my modified unit test failed with all versions. However, the repo whose Travis log I linked already has `sphinx.ext.mathjax`.

Thanks @ericholscher, and sorry if I opened this in the wrong project. I now see the same thing as you: Sphinx 1.7.9: no error. Sphinx 1.8.0: error.

**Comment by ambiso** [comment] 2018-11-16 00:00
Can confirm the workaround to use Sphinx 1.7:

`pip install sphinx==1.7`

**Comment by zonca** [comment] 2019-02-21 01:59
how do I force 1.7 on readthedocs? 

the problem is that it runs:

   conda install --yes --quiet --name latest mock pillow sphinx sphinx_rtd_theme

after installing the custom user environment and that forces `sphinx` to upgrade.

I even tried to install `mock pillow sphinx=1.7 sphinx_rtd_theme` in my user environment but still the command above upgrades to 1.8.

**Comment by talengu** [comment] 2019-05-04 06:02
Encounter the same problem. sphinx version 2.0.1.
But OK with 1.7.9.

**Comment by diegoquintanav** [comment] 2019-05-20 17:10
I'm also using `1.7.9`,  along with these dependencies (inside a Flask Application)

```bash
root@ac0b60dc58c3:/src/app# pip freeze | grep -iwE '(sphinx|recommonmark|docutils|websupport)'
docutils==0.14
recommonmark==0.5.0
Sphinx==1.7.9
sphinx-rtd-theme==0.4.3
sphinxcontrib-websupport==1.1.2 # adds WebSupport
```

And I'm running into this error

```
root@4e00e44b18a6:/src/app# python build_docs.py 
Running Sphinx v1.7.9
loading translations [es]... done
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [websupport]: targets for 9 source files that are out of date
updating environment: 9 added, 0 changed, 0 removed
/src/venv/lib/python3.6/site-packages/recommonmark/parser.py:65: UserWarning: Container node skipped: type=document                                                                        
  warn("Container node skipped: type={0}".format(mdnode.t))
Traceback (most recent call last):rs/ise                                                                                                                                                   
  File "build_docs.py", line 27, in <module>
    build_docs()
  File "build_docs.py", line 23, in build_docs
    support.build()
  File "/src/venv/lib/python3.6/site-packages/sphinxcontrib/websupport/core.py", line 146, in build
    app.build()
  File "/src/venv/lib/python3.6/site-packages/sphinx/application.py", line 331, in build
    self.builder.build_update()
  File "/src/venv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 342, in build_update
    'out of date' % len(to_build))
  File "/src/venv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 355, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/src/venv/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 568, in update
    self._read_serial(docnames, self.app)
  File "/src/venv/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 587, in _read_serial
    self.read_doc(docname, app)
  File "/src/venv/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 662, in read_doc
    doctree = read_doc(self.app, self, self.doc2path(docname))
  File "/src/venv/lib/python3.6/site-packages/sphinx/io.py", line 302, in read_doc
    pub.publish()
  File "/src/venv/lib/python3.6/site-packages/docutils/core.py", line 218, in publish
    self.apply_transforms()
  File "/src/venv/lib/python3.6/site-packages/docutils/core.py", line 199, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/src/venv/lib/python3.6/site-packages/sphinx/transforms/__init__.py", line 96, in apply_transforms
    Transformer.apply_transforms(self)
  File "/src/venv/lib/python3.6/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/src/venv/lib/python3.6/site-packages/recommonmark/transform.py", line 328, in apply
    self.traverse(self.document)
  File "/src/venv/lib/python3.6/site-packages/recommonmark/transform.py", line 308, in traverse
    self.traverse(child)
  File "/src/venv/lib/python3.6/site-packages/recommonmark/transform.py", line 308, in traverse
    self.traverse(child)
  File "/src/venv/lib/python3.6/site-packages/recommonmark/transform.py", line 308, in traverse
    self.traverse(child)
  File "/src/venv/lib/python3.6/site-packages/recommonmark/transform.py", line 298, in traverse
    newnode = self.find_replace(c)
  File "/src/venv/lib/python3.6/site-packages/recommonmark/transform.py", line 282, in find_replace
    newnode = self.auto_inline_code(node)
  File "/src/venv/lib/python3.6/site-packages/recommonmark/transform.py", line 211, in auto_inline_code
    return self.state_machine.run_role('math', content=content)
  File "/src/venv/lib/python3.6/site-packages/recommonmark/states.py", line 133, in run_role
    content=content)
  File "/src/venv/lib/python3.6/site-packages/docutils/parsers/rst/roles.py", line 356, in math_role
    text = rawtext.split('`')[1]
IndexError: list index out of range
```
While trying to debug this, I found out that if I downgrade `sphinxcontribwebsupport` to `1.1.0` the error dissapears. 

Hope this helps someone.

**Comment by htleeab** [comment] 2020-01-03 06:55
It seems that there are multiple pull requests for this fix but none of them is merged.
There are simple workaround ``$` abc `$``

**Comment by CodingCattwo** [comment] 2020-04-23 06:57
Encounter the same problem. sphinx version 2.0.1.

> Encounter the same problem. sphinx version 2.0.1.
> But OK with 1.7.9.

try sphinx 1.7.9 or 1.6.9, failed

**Comment by Dylan-JW** [comment] 2020-09-16 17:50
I encounter this issue as well with sphinx 3.2.1

**Closed** 2022-03-24 20:30 UTC
